---
title: "Data Analysis"
author: "Candela Cerpa & Samantha Pace & Vinny Whatley"
date: "2023-12-10"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#install.packages("tidyverse") # This code chunk installs the tidyverse package.
#install.packages("lubridate") # This code chunk install lubridate package.
#install.packages("here") # This code chunk will install the here package.
#install.packages("zoo")
#install.packages("Kendall")
#install.packages("tseries")
# they are all now comments so it will knit.

library(tidyverse)
library(lubridate)
library(here)
library(ggplot2)
library(ggthemes)
library(cowplot)
library(Kendall)
library(tseries)
here()
```

```{r Load processed files}
Phoenix <- read.csv(here("./Data/Processed/PhoenixAZ_processed.csv"),
                    stringsAsFactors = TRUE) %>% 
  mutate(Date = ymd(Date))

FountainHills <- read.csv(here("./Data/Processed/FountainHillsAZ_processed.csv"),
                          stringsAsFactors = TRUE) %>% 
  mutate(Date = ymd(Date))

LasVegas <- read.csv(here("./Data/Processed/LasVegasNV_processed.csv"),
                     stringsAsFactors = TRUE) %>% 
  mutate(Date = ymd(Date))

Pahrump <- read.csv(here("./Data/Processed/PahrumpNV_processed.csv"),
                    stringsAsFactors = TRUE) %>% 
  mutate(Date = ymd(Date))

SanDiego <- read.csv(here("./Data/Processed/SanDiegoCA_processed.csv"),
                     stringsAsFactors = TRUE) %>%
  mutate(Date = ymd(Date))

Ramona <- read.csv(here("./Data/Processed/RamonaCA_processed.csv"),
                   stringsAsFactors = TRUE) %>% 
  mutate(Date = ymd(Date))
```

```{r set theme}
theme_EDA <- theme_base() +
  theme(
   plot.background = element_rect(
      color = "black",
      fill = "gray"
    ),
    legend.position = "right",
    complete = TRUE
  )
theme_set(theme_EDA)

#monthly labels
month_lab = tibble(doy = yday(as.Date(c("1980-02-15", "1980-04-15",
                                          "1980-06-15", "1980-08-15",
                                          "1980-10-15", "1980-12-15"))),
                     lab = c("Feb", "Apr", "Jun", "Aug", "Oct", "Dec"))
```

```{r time series objects for min and max temperatures}
#Creating univariate time series objects for min & max temperature for each site
#Pheonix
Phoenix_temp_min_ts <- ts(Phoenix$Daily_Temp_Min,
                            start = c(1980, 1),
                            frequency = 365)

Phoenix_temp_max_ts <- ts(Phoenix$Daily_Temp_Max, 
                            start = c(1980, 1),
                            frequency = 365)

#Fountain Hills
FountainHills_temp_min_ts <- ts(FountainHills$Daily_Temp_Min,
                            start = c(1980, 1),
                            frequency = 365)

FountainHills_temp_max_ts <- ts(FountainHills$Daily_Temp_Max, 
                            start = c(1980, 1),
                            frequency = 365)

#Las Vegas
LasVegas_temp_min_ts <- ts(LasVegas$Daily_Temp_Min,
                            start = c(1972, 1),
                            frequency = 365)

LasVegas_temp_max_ts <- ts(LasVegas$Daily_Temp_Max, 
                            start = c(1972, 1),
                            frequency = 365)

#Pahrump
Pahrump_temp_min_ts <- ts(Pahrump$Daily_Temp_Min,
                            start = c(1972, 1),
                            frequency = 365)

Pahrump_temp_max_ts <- ts(Pahrump$Daily_Temp_Max, 
                            start = c(1972, 1),
                            frequency = 365)

#San Diego
SanDiego_temp_min_ts <- ts(SanDiego$Daily_Temp_Min,
                            start = c(1972, 1),
                            frequency = 365)

SanDiego_temp_max_ts <- ts(SanDiego$Daily_Temp_Max, 
                            start = c(1972, 1),
                            frequency = 365)

#Ramona
Ramona_temp_min_ts <- ts(Ramona$Daily_Temp_Min,
                            start = c(1998, 1),
                            frequency = 365)

Ramona_temp_max_ts <- ts(Ramona$Daily_Temp_Max, 
                            start = c(1998, 1),
                            frequency = 365)
```

```{r decomposing time series objects for min and max temperatures}
# Decompose each time series (ts) object
#Phoenix
Phoenix_temp_min_ts_Decomposed <- stl(Phoenix_temp_min_ts,
                                      s.window = "periodic")
plot(Phoenix_temp_min_ts_Decomposed)

Phoenix_temp_max_ts_Decomposed <- stl(Phoenix_temp_max_ts,
                                      s.window = "periodic")
plot(Phoenix_temp_max_ts_Decomposed)

#Fountain Hills
FountainHills_temp_min_ts_Decomposed <- stl(FountainHills_temp_min_ts,
                                            s.window = "periodic")
plot(FountainHills_temp_min_ts_Decomposed)

FountainHills_temp_max_ts_Decomposed <- stl(FountainHills_temp_max_ts,
                                            s.window = "periodic")
plot(FountainHills_temp_max_ts_Decomposed)

#Las Vegas
LasVegas_temp_min_ts_Decomposed <- stl(LasVegas_temp_min_ts,
                                       s.window = "periodic")
plot(LasVegas_temp_min_ts_Decomposed)

LasVegas_temp_max_ts_Decomposed <- stl(LasVegas_temp_max_ts,
                                       s.window = "periodic")
plot(LasVegas_temp_max_ts_Decomposed)

#Pahrump
Pahrump_temp_min_ts_Decomposed <- stl(Pahrump_temp_min_ts,
                                      s.window = "periodic")
plot(Pahrump_temp_min_ts_Decomposed)

Pahrump_temp_max_ts_Decomposed <- stl(Pahrump_temp_max_ts,
                                      s.window = "periodic")
plot(Pahrump_temp_max_ts_Decomposed)

#San Diego
SanDiego_temp_min_ts_Decomposed <- stl(SanDiego_temp_min_ts,
                                       s.window = "periodic")
plot(SanDiego_temp_min_ts_Decomposed)

SanDiego_temp_max_ts_Decomposed <- stl(SanDiego_temp_max_ts,
                                       s.window = "periodic")
plot(SanDiego_temp_max_ts_Decomposed)

#Ramona
Ramona_temp_min_ts_Decomposed <- stl(Ramona_temp_min_ts,
                                    s.window = "periodic")
plot(Ramona_temp_min_ts_Decomposed)

Ramona_temp_max_ts_Decomposed <- stl(Ramona_temp_max_ts,
                                     s.window = "periodic")
plot(Ramona_temp_max_ts_Decomposed)
```

```{r SMK tests for min and max temperatures}
#Run Seasonal Mann Kendall Tests

#Phoenix
Phoenix_temp_max_trend <- SeasonalMannKendall(Phoenix_temp_max_ts)
summary(Phoenix_temp_max_trend)

#p-value: <2.22 e-16 <0.05 so null hypothesis (data is stationary) is rejected
#tau value: 0.0617 slope of the trend line

Phoenix_temp_min_trend <- SeasonalMannKendall(Phoenix_temp_min_ts)
summary(Phoenix_temp_min_trend)

#p-value: <2.22 e-16 <0.05 so null hypothesis (data is stationary) is rejected
#tau value: 0.0951 slope of the trend line

#Fountain Hills
FountainHills_temp_max_trend <- SeasonalMannKendall(FountainHills_temp_max_ts)
summary(FountainHills_temp_max_trend)

#p-value: 7.6637e-07 <0.05 so null hypothesis (data is stationary) is rejected
#tau value: -0.0282 slope of the trend line

FountainHills_temp_min_trend <- SeasonalMannKendall(FountainHills_temp_min_ts)
summary(FountainHills_temp_min_trend)

#p-value: <2.22e-16 <0.05 so null hypothesis (data is stationary) is rejected
#tau value: 0.0979 slope of the trend line

#Las Vegas
LasVegas_temp_max_trend <- SeasonalMannKendall(LasVegas_temp_max_ts)
summary(LasVegas_temp_max_trend)

#p-value: <2.22 e-16 <0.05 so null hypothesis (data is stationary) is rejected
#tau value: 0.0671 slope of the trend line

LasVegas_temp_min_trend <- SeasonalMannKendall(LasVegas_temp_min_ts)
summary(LasVegas_temp_min_trend)

#p-value: <2.22 e-16 <0.05 so null hypothesis (data is stationary) is rejected
#tau value: 0.29 slope of the trend line

#Pahrump
Pahrump_temp_max_trend <- SeasonalMannKendall(Pahrump_temp_max_ts)
summary(Pahrump_temp_max_trend)

#p-value: <2.22 e-16 <0.05 so null hypothesis (data is stationary) is rejected
#tau value: 0.0482 slope of the trend line

Pahrump_temp_min_trend <- SeasonalMannKendall(Pahrump_temp_min_ts)
summary(Pahrump_temp_min_trend)

#p-value: <2.22 e-16 <0.05 so null hypothesis (data is stationary) is rejected
#tau value: 0.0678 slope of the trend line

#San Diego
SanDiego_temp_max_trend <- SeasonalMannKendall(SanDiego_temp_max_ts)
summary(SanDiego_temp_max_trend)

#p-value: 0.00089098 <0.05 so null hypothesis (data is stationary) is rejected
#tau value: 0.0173 slope of the trend line

SanDiego_temp_min_trend <- SeasonalMannKendall(SanDiego_temp_min_ts)
summary(SanDiego_temp_min_trend)

#p-value: 0.00051036 <0.05 so null hypothesis (data is stationary) is rejected
#tau value: -0.0182 slope of the trend line

#Ramona
Ramona_temp_max_trend <- SeasonalMannKendall(Ramona_temp_max_ts)
summary(Ramona_temp_max_trend)

#p-value: <2.22 e-16 <0.05 so null hypothesis (data is stationary) is rejected
#tau value: -0.112 slope of the trend line

Ramona_temp_min_trend <- SeasonalMannKendall(Ramona_temp_min_ts)
summary(Ramona_temp_min_trend)

#p-value: <2.22 e-16 <0.05 so null hypothesis (data is stationary) is rejected
#tau value: -0.0912 slope of the trend line
```

``` {r plots for min and max temperatures, fig.width=8, fig.height=14}
#Phoenix plot
Phoenix_plot_temp <- ggplot(Phoenix, aes(x = Date)) +
  geom_line(aes(y = Daily_Temp_Max, color = "Max Temp")) + 
  geom_smooth(aes(y = Daily_Temp_Max), method = lm, color = "red") + 
  geom_line(aes(y = Daily_Temp_Min, color = "Min Temp")) + 
  geom_smooth(aes(y = Daily_Temp_Min), method = lm, color = "blue") + 
  scale_color_manual(values = c("pink", "lightblue")) +
  labs(title = "Phoenix (1980-2022)", x = "Year",
       y = "Daily Temp Peaks (°F)", color = "Legend")
print(Phoenix_plot_temp)

#Fountain Hills plot
FountainHills_plot_temp <- ggplot(FountainHills, aes(x = Date)) +
  geom_line(aes(y = Daily_Temp_Max, color = "Max Temp")) + 
  geom_smooth(aes(y = Daily_Temp_Max), method = lm, color = "red") + 
  geom_line(aes(y = Daily_Temp_Min, color = "Min Temp")) + 
  geom_smooth(aes(y = Daily_Temp_Min), method = lm, color = "blue") + 
  scale_color_manual(values = c("pink", "lightblue")) +
  labs(title = "Fountain Hills (1980-2022)", x = "Year",
       y = "Daily Temp Peaks (°F)", color = "Legend")
print(FountainHills_plot_temp)

#Las Vegas
LasVegas_plot_temp <- ggplot(LasVegas, aes(x = Date)) +
  geom_line(aes(y = Daily_Temp_Max, color = "Max Temp")) + 
  geom_smooth(aes(y = Daily_Temp_Max), method = lm, color = "red") + 
  geom_line(aes(y = Daily_Temp_Min, color = "Min Temp")) + 
  geom_smooth(aes(y = Daily_Temp_Min), method = lm, color = "blue") + 
  scale_color_manual(values = c("pink", "lightblue")) +
  labs(title = "Las Vegas (1972-2022)", x = "Year",
       y = "Daily Temp Peaks (°F)", color = "Legend")
print(LasVegas_plot_temp)

#Pahrump
Pahrump_plot_temp <- ggplot(Pahrump, aes(x = Date)) +
  geom_line(aes(y = Daily_Temp_Max, color = "Max Temp")) + 
  geom_smooth(aes(y = Daily_Temp_Max), method = lm, color = "red") + 
  geom_line(aes(y = Daily_Temp_Min, color = "Min Temp")) + 
  geom_smooth(aes(y = Daily_Temp_Min), method = lm, color = "blue") + 
  scale_color_manual(values = c("pink", "lightblue")) +
  labs(title = "Pahrump (1972-2022)", x = "Year",
       y = "Daily Temp Peaks (°F)", color = "Legend")
print(Pahrump_plot_temp)

#San Diego
SanDiego_plot_temp <- ggplot(SanDiego, aes(x = Date)) +
  geom_line(aes(y = Daily_Temp_Max, color = "Max Temp")) + 
  geom_smooth(aes(y = Daily_Temp_Max), method = lm, color = "red") + 
  geom_line(aes(y = Daily_Temp_Min, color = "Min Temp")) + 
  geom_smooth(aes(y = Daily_Temp_Min), method = lm, color = "blue") + 
  scale_color_manual(values = c("pink", "lightblue")) +
  labs(title = "San Diego (1972-2022)", x = "Year",
       y = "Daily Temp Peaks (°F)", color = "Legend")
print(SanDiego_plot_temp)

#Ramona
Ramona_plot_temp <- ggplot(Ramona, aes(x = Date)) +
  geom_line(aes(y = Daily_Temp_Max, color = "Max Temp")) + 
  geom_smooth(aes(y = Daily_Temp_Max), method = lm, color = "red") + 
  geom_line(aes(y = Daily_Temp_Min, color = "Min Temp")) + 
  geom_smooth(aes(y = Daily_Temp_Min), method = lm, color = "blue") + 
  scale_color_manual(values = c("pink", "lightblue")) +
  labs(title = "Ramona (1998-2022)", x = "Year",
       y = "Daily Temp Peaks (°F)", color = "Legend")
print(Ramona_plot_temp)

#extract a legend from one of the plots, make it into an object
plot_legend <- get_legend(Ramona_plot_temp + theme(legend.position = "top")

#add the plots without legends to a cowplot
temp_plots <- plot_grid(
  Phoenix_plot_temp + theme(legend.position = "none"),
  FountainHills_plot_temp + theme(legend.position = "none"),
  LasVegas_plot_temp + theme(legend.position = "none"),
  Pahrump_plot_temp + theme(legend.position = "none"),
  SanDiego_plot_temp + theme(legend.position = "none"),
  Ramona_plot_temp + theme(legend.position = "none"),
  ncol = 2, nrow = 3)
print(temp_plots)

#combine plots and legend
temperature_plots <- plot_grid(temp_plots, plot_legend,
                               ncol = 2, nrow = 3)
print(temperature_plots)
```

```{r creating time series objects for heat and cool degrees}
#Creating univariate time series objects for heat and cool degrees for each major city

#Phoenix
Phoenix_heatdegrees_ts <- ts(Phoenix$Heat_Degrees, 
                            start = c(1980, 1),
                            frequency = 365)

Phoenix_cooldegrees_ts <- ts(Phoenix$Cool_Degrees, 
                            start = c(1980, 1),
                            frequency = 365)

#Las Vegas
LasVegas_heatdegrees_ts <- ts(LasVegas$Heat_Degrees,
                              start = c(1972, 1),
                              frequency = 365)

LasVegas_cooldegrees_ts <- ts(LasVegas$Cool_Degrees,
                              start = c(1972, 1),
                              frequency = 365)

#San Diego
SanDiego_heatdegrees_ts <- ts(SanDiego$Heat_Degrees,
                              start = c(1972, 1),
                              frequency = 365)

SanDiego_cooldegrees_ts <- ts(SanDiego$Cool_Degrees,
                              start = c(1972, 1),
                              frequency = 365)
```

```{r decomposing time series objects for heat and cool degrees}
# Decomposing each ts object

Phoenix_heatdegrees_ts_Decomposed <-
  stl(Phoenix_heatdegrees_ts, s.window = "periodic")

plot(Phoenix_heatdegrees_ts_Decomposed)

Phoenix_cooldegrees_ts_Decomposed <-
  stl(Phoenix_cooldegrees_ts, s.window = "periodic")

plot(Phoenix_cooldegrees_ts_Decomposed)

#Las Vegas decomposition and plot

LasVegas_heatdegrees_ts_Decomposed <-
  stl(LasVegas_heatdegrees_ts, s.window = "periodic")

plot(LasVegas_heatdegrees_ts_Decomposed)

LasVegas_cooldegrees_ts_Decomposed <-
  stl(LasVegas_cooldegrees_ts, s.window = "periodic")

plot(LasVegas_cooldegrees_ts_Decomposed)

# San Diego decompostion and plot

SanDiego_heatdegrees_ts_Decomposed <-
  stl(SanDiego_heatdegrees_ts, s.window = "periodic")

plot(SanDiego_heatdegrees_ts_Decomposed)

SanDiego_cooldegrees_ts_Decomposed <-
  stl(SanDiego_cooldegrees_ts, s.window = "periodic")

plot(SanDiego_cooldegrees_ts_Decomposed)

```

```{r SMK test for heating and cooling degree days}
# Run Seasonal Mann Kendall Test for heating degree days

#Phoenix
Phoenix_heatdegrees_trend <- SeasonalMannKendall(Phoenix_heatdegrees_ts)
Phoenix_heatdegrees_trend
# p value =3.0198e-13 ; reject the null hypothesis (data is stationary)
# tau = -0.0592 (trendline slope)

#Las Vegas
LasVegas_heatdegrees_trend <- SeasonalMannKendall(LasVegas_heatdegrees_ts)
LasVegas_heatdegrees_trend
# p value =< 2.22e-16 ; reject the null hypothesis (data is stationary)
# tau = -0.16 (trendline slope)

#San Diego
SanDiego_heatdegrees_trend <- SeasonalMannKendall(SanDiego_heatdegrees_ts)
SanDiego_heatdegrees_trend
# pvalue =0.49529 ; CANNOT reject the null hypothesis, data is stationary
# tau = -0.00414 (trendline slope)
```

```{r Seasonal Mann Kendall Test for cooling degree days}
# Run Seasonal Mann Kendall Test for cooling degree days

Phoenix_cooldegrees_trend <-SeasonalMannKendall(Phoenix_cooldegrees_ts)
Phoenix_cooldegrees_trend
#p value =< 2.22e-16 ; reject the null hypothesis (data is stationary)
# tau = 0.0983 (slope of trend)

#Las Vegas
LasVegas_cooldegrees_trend <-SeasonalMannKendall(LasVegas_cooldegrees_ts)
LasVegas_cooldegrees_trend
# p value is =< 2.22e-16 ; reject the null hypothesis (data is stationary) 
# tau = 0.189 (slope of the trend)

#San Diego
SanDiego_cooldegrees_trend <- SeasonalMannKendall(SanDiego_cooldegrees_ts)
SanDiego_cooldegrees_trend
# p value is 0.36317 ; CANNOT reject the null 
# tau = -0.00542
```


```{r Summary of data for each city}
summary(LasVegas)

summary(Pahrump)

summary(Phoenix)

summary(FountainHills)

summary(SanDiego)

summary(Ramona)
```

```{r Fitering each data set for companion city}
#Filtering Datasets from 1980 to 2022
LasVegasMetro <- LasVegas %>%
  filter(Year >= 1972 & Year <= 2022)

PahrumpSuburban <- Pahrump %>%
  filter(Year >= 1972 & Year <= 2022)

PhoenixMetro <- Phoenix %>%
  filter(Year >= 1980 & Year <= 2022)

FountainHillsSuburban <- FountainHills %>%
  filter(Year >= 1980 & Year <= 2022)

SanDiegoMetro <- SanDiego %>%
  filter(Year >= 1998 & Year <= 2022)

RamonaSuburban <- Ramona %>%
  filter(Year >= 1998 & Year <= 2022)

```

```{r combine nevada cities }
# Combine datasets by rows
Nevada_data <- rbind(LasVegasMetro, PahrumpSuburban)

Nevada_data <- Nevada_data %>%
  select(Location, Year, Heat_Degrees, Cool_Degrees)

# Perform ANOVA test for Heat_Degrees by Location and Year
Nevada_anova_result_heat <- aov(Heat_Degrees ~ Location*Year, data = Nevada_data)

# Perform ANOVA test for Cool_Degrees by Location and Year
Nevada_anova_result_cool <- aov(Cool_Degrees ~ Location*Year, data = Nevada_data)

# Summary of ANOVA results for Heat_Degrees
summary(Nevada_anova_result_heat) 


# Summary of ANOVA results for Cool_Degrees
summary(Nevada_anova_result_cool)

# Extract F-values using the summary function
Nevada_summary_anova_heat <- summary(Nevada_anova_result_heat)
Nevada_summary_anova_cool <- summary(Nevada_anova_result_cool)


```

```{r combine Arizona cities}
# Combine datasets by rows
Arizona_data <- rbind(PhoenixMetro, FountainHillsSuburban)

Arizona_data <- Arizona_data %>%
  select(Location, Year, Heat_Degrees, Cool_Degrees)

# Perform ANOVA test for Heat_Degrees by Location and Year
Arizona_anova_result_heat <- aov(Heat_Degrees ~ Location*Year, data = Arizona_data)

# Perform ANOVA test for Cool_Degrees by Location and Year
Arizona_anova_result_cool <- aov(Cool_Degrees ~ Location*Year, data = Arizona_data)

# Summary of ANOVA results for Heat_Degrees
summary(Arizona_anova_result_heat) 


# Summary of ANOVA results for Cool_Degrees
summary(Arizona_anova_result_cool)

# Extract F-values using the summary function
Arizona_summary_anova_heat <- summary(Arizona_anova_result_heat)
Arizona_summary_anova_cool <- summary(Arizona_anova_result_cool)
```

```{r combine California cities}
# Combine datasets by rows
California_data <- rbind(SanDiegoMetro, RamonaSuburban)

California_data <- California_data %>%
  select(Location, Year, Heat_Degrees, Cool_Degrees)

# Perform ANOVA test for Heat_Degrees by Location and Year
California_anova_result_heat <- aov(Heat_Degrees ~ Location*Year, data = California_data)

# Perform ANOVA test for Cool_Degrees by Location and Year
California_anova_result_cool <- aov(Cool_Degrees ~ Location*Year, data = California_data)

# Summary of ANOVA results for Heat_Degrees
summary(California_anova_result_heat) 


# Summary of ANOVA results for Cool_Degrees
summary(California_anova_result_cool)

# Extract F-values using the summary function
California_summary_anova_heat <- summary(California_anova_result_heat)
California_summary_anova_cool <- summary(California_anova_result_cool)
```


```{r Nevada Kable}
# Extract the aov table from the summary.aov object
Nevada_anova_table_heat <- summary(Nevada_anova_result_heat)[[1]]

# Convert the ANOVA table to a data frame
Nevada_anova_df_heat <- as.data.frame(Nevada_anova_table_heat)

# Display the ANOVA table using kable
kable(Nevada_anova_df_heat, caption = "ANOVA Summary Table for Nevada Heat_Degrees")

# Extract the aov table from the summary.aov object
Nevada_anova_table_cool <- summary(Nevada_anova_result_cool)[[1]]

# Convert the ANOVA table to a data frame
Nevada_anova_df_cool <- as.data.frame(Nevada_anova_table_cool)

# Display the ANOVA table using kable
kable(Nevada_anova_df_cool, caption = "ANOVA Summary Table for Nevada Cool_Degrees")

```

```{r Arizona Kable}
# Extract the aov table from the summary.aov object
# Extract the aov table from the summary.aov object
Arizona_anova_table_heat <- summary(Arizona_anova_result_heat)[[1]]

# Convert the ANOVA table to a data frame
Arizona_anova_df_heat <- as.data.frame(Arizona_anova_table_heat)

# Display the ANOVA table using kable
kable(Arizona_anova_df_heat, caption = "ANOVA Summary Table for Arizona Heat_Degrees")

# Extract the aov table from the summary.aov object
Arizona_anova_table_cool <- summary(Arizona_anova_result_cool)[[1]]

# Convert the ANOVA table to a data frame
Arizona_anova_df_cool <- as.data.frame(Arizona_anova_table_cool)

# Display the ANOVA table using kable
kable(Arizona_anova_df_cool, caption = "ANOVA Summary Table for Arizona Cool_Degrees")
```

```{r California Kable}
# Extract the aov table from the summary.aov object
California_anova_table_heat <- summary(California_anova_result_heat)[[1]]

# Convert the ANOVA table to a data frame
California_anova_df_heat <- as.data.frame(California_anova_table_heat)

# Display the ANOVA table using kable
kable(California_anova_df_heat, caption = "ANOVA Summary Table for California Heat_Degrees")

# Extract the aov table from the summary.aov object
California_anova_table_cool <- summary(California_anova_result_cool)[[1]]

# Convert the ANOVA table to a data frame
California_anova_df_cool <- as.data.frame(California_anova_table_cool)

# Display the ANOVA table using kable
kable(California_anova_df_cool, caption = "ANOVA Summary Table for California Cool_Degrees")
```


```{r Creating Bar plot of F-values, Nevada data}

# extracted F-values
Nevada_f_values_heat <- c(803.9, 88.6, 36.4)  
Nevada_f_values_cool <- c(1228.7, 153.4, 36.4)  

# Combine the F-values into a matrix
Nevada_f_values_matrix <- matrix(c(Nevada_f_values_heat, Nevada_f_values_cool), nrow = 3, byrow = TRUE)

# Names for the bars (change or customize as needed)
bar_names <- c("Heat Values", "Cool Values")

# Assign colors to bars corresponding to each factor
colors <- c(rep("red", length(Nevada_f_values_heat)), rep("blue", length(Nevada_f_values_cool)))


# Check the number of names and columns in the matrix
if (length(bar_names) != ncol(Nevada_f_values_matrix)) {
  stop("Incorrect number of names for the columns in the matrix.")
} else {
  # Create a bar plot with specific colors for each bar
  barplot(Nevada_f_values_matrix, beside = TRUE,
          col = colors,
          names.arg = bar_names,
          main = "ANOVA F-values for Heat_Degrees and Cool_Degrees",
          ylab = "F-value")


# Adding custom labels above the bars for Heat Values with different distances
text(1:3 + 0.25 * c(1.5, 1.5, 2.5), par("usr")[4] + 1, c("Location", "Year", "Location: Year"), srt = 0, adj = c(0.5, 2), xpd = TRUE)

# Adding custom labels above the bars for Cool Values
text((1:3) + 4.5 + 0.25 * c(0, 0.25, 1), par("usr")[4] + 9, c("Location", "Year", "Location: Year"), srt = 0, adj = c(0.5, 0), xpd = TRUE)
}

```

```{r Creating Bar plot of F-values, Arizona data}
# extracted F-values
Arizona_f_values_heat <- c(236.3, 44.5, 3.7)  
Arizona_f_values_cool <- c(238.2, 25.2, 6.8)  

# Combine the F-values into a matrix
Arizona_f_values_matrix <- matrix(c(Arizona_f_values_heat, Arizona_f_values_cool), nrow = 3, byrow = TRUE)

# Names for the bars (change or customize as needed)
bar_names <- c("Heat Values", "Cool Values")

# Assign colors to bars corresponding to each factor
colors <- c(rep("red", length(Arizona_f_values_heat)), rep("blue", length(Arizona_f_values_cool)))


# Check the number of names and columns in the matrix
if (length(bar_names) != ncol(Arizona_f_values_matrix)) {
  stop("Incorrect number of names for the columns in the matrix.")
} else {
  # Create a bar plot with specific colors for each bar
  barplot(Arizona_f_values_matrix, beside = TRUE,
          col = colors,
          names.arg = bar_names,
          main = "ANOVA F-values for Heat_Degrees and Cool_Degrees",
          ylab = "F-value")

# Adding custom labels above the bars for Heat Values with different distances
text(1:3 + 0.25 * c(1.5, 1.5, 2.75), par("usr")[4] + 25, c("Location", "Year", "Location: Year"), srt = 0, adj = c(0.5, 2), xpd = TRUE)

# Adding custom labels above the bars for Cool Values
text((1:3) + 4.5 + 0.25 * c(0, 0.5, 1), par("usr")[4] + 5, c("Location", "Year", "Location: Year"), srt = 0, adj = c(0.5, 0), xpd = TRUE)
}
```

```{r Creating Bar plot of F-values, California data}
# extracted F-values
California_f_values_heat <- c(1870.4, 114.2, 0.2)  
California_f_values_cool <- c(18.9, 237.4, 7.3)  

# Combine the F-values into a matrix
California_f_values_matrix <- matrix(c(California_f_values_heat, California_f_values_cool), nrow = 3, byrow = TRUE)

# Names for the bars (change or customize as needed)
bar_names <- c("Heat Values", "Cool Values")

# Assign colors to bars corresponding to each factor
colors <- c(rep("red", length(California_f_values_heat)), rep("blue", length(California_f_values_cool)))


# Check the number of names and columns in the matrix
if (length(bar_names) != ncol(California_f_values_matrix)) {
  stop("Incorrect number of names for the columns in the matrix.")
} else {
  # Create a bar plot with specific colors for each bar
  barplot(California_f_values_matrix, beside = TRUE,
          col = colors,
          names.arg = bar_names,
          main = "ANOVA F-values for Heat_Degrees and Cool_Degrees",
          ylab = "F-value")

# Adding custom labels above the bars for Heat Values with different distances
text(1:3 + 0.25 * c(1.5, 1.5, 2.75), par("usr")[4] + 200, c("Location", "Year", "Location: Year"), srt = 0, adj = c(0.5, 2), xpd = TRUE)

# Adding custom labels above the bars for Cool Values
text((1:3) + 4.5 + 0.25 * c(0, 0.2, 1), par("usr")[4] - 900, c("Location", "Year", "Location: Year"), srt = 0, adj = c(0.5, 0), xpd = TRUE)
}
```