---
title: "Data Exploration"
author: "Candela Cerpa & Samantha Pace & Vinny Whatley"
date: "2023-11-20"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages(ggplot2)
#install.packages(ggpthemes)
#install.packages(cowplot)

library(tidyverse)
library(lubridate)
library(here)
library(ggplot2)
library(ggthemes)
library(cowplot)

# Working Directory with the here() command
here()
```

```{r Load processed files}
Phoenix <- read.csv(here("./Data/Processed/PhoenixAZ_processed.csv"),
                    stringsAsFactors = TRUE) %>% 
  mutate(Date = ymd(Date))

FountainHills <- read.csv(here("./Data/Processed/FountainHillsAZ_processed.csv"),
                          stringsAsFactors = TRUE) %>% 
  mutate(Date = ymd(Date))

LasVegas <- read.csv(here("./Data/Processed/LasVegasNV_processed.csv"),
                     stringsAsFactors = TRUE) %>% 
  mutate(Date = ymd(Date))

Pahrump <- read.csv(here("./Data/Processed/PahrumpNV_processed.csv"),
                    stringsAsFactors = TRUE) %>% 
  mutate(Date = ymd(Date))

SanDiego <- read.csv(here("./Data/Processed/SanDiegoCA_processed.csv"),
                     stringsAsFactors = TRUE) %>%
  mutate(Date = ymd(Date))

Ramona <- read.csv(here("./Data/Processed/RamonaCA_processed.csv"),
                   stringsAsFactors = TRUE) %>% 
  mutate(Date = ymd(Date))
```


```{r Calculating Heating and Cooling Degree Days}
#1. Create a column for heating degrees with 0s
#2. Create a column for heating degrees with 0s
#3. Calculate heating degrees by finding the mean temp that's below 65F then
#subtracting the mean temp from 65
#4. Calculate cooling degrees by finding the mean temp that's above 65F then
#subtracting 65 from the mean temp

Phoenix$Heat_Degrees <- rep(0)
Phoenix$Cool_Degrees <- rep(0)
Phoenix$Heat_Degrees [Phoenix$Temp_Avg < 65] <-
  65 - Phoenix$Temp_Avg [Phoenix$Temp_Avg < 65]
Phoenix$Cool_Degrees [Phoenix$Temp_Avg > 65] <-
  Phoenix$Temp_Avg [Phoenix$Temp_Avg > 65] - 65

FountainHills$Heat_Degrees <- rep(0)
FountainHills$Cool_Degrees <- rep(0)
FountainHills$Heat_Degrees [FountainHills$Temp_Avg < 65] <-
  65 - FountainHills$Temp_Avg [FountainHills$Temp_Avg < 65]
FountainHills$Cool_Degrees [FountainHills$Temp_Avg > 65] <-
  FountainHills$Temp_Avg [FountainHills$Temp_Avg > 65] - 65

LasVegas$Heat_Degrees <- rep(0)
LasVegas$Cool_Degrees <- rep(0)
LasVegas$Heat_Degrees [LasVegas$Temp_Avg < 65] <-
  65 - LasVegas$Temp_Avg [LasVegas$Temp_Avg < 65]
LasVegas$Cool_Degrees [LasVegas$Temp_Avg > 65] <-
  LasVegas$Temp_Avg [LasVegas$Temp_Avg > 65] - 65

Pahrump$Heat_Degrees <- rep(0)
Pahrump$Cool_Degrees <- rep(0)
Pahrump$Heat_Degrees [Pahrump$Temp_Avg < 65] <-
  65 - Pahrump$Temp_Avg [Pahrump$Temp_Avg < 65]
Pahrump$Cool_Degrees [Pahrump$Temp_Avg > 65] <-
  Pahrump$Temp_Avg [Pahrump$Temp_Avg > 65] - 65

SanDiego$Heat_Degrees <- rep(0)
SanDiego$Cool_Degrees <- rep(0)
SanDiego$Heat_Degrees [SanDiego$Temp_Avg < 65] <-
  65 - SanDiego$Temp_Avg [SanDiego$Temp_Avg < 65]
SanDiego$Cool_Degrees [SanDiego$Temp_Avg > 65] <-
  SanDiego$Temp_Avg [SanDiego$Temp_Avg > 65] - 65

Ramona$Heat_Degrees <- rep(0)
Ramona$Cool_Degrees <- rep(0)
Ramona$Heat_Degrees [Ramona$Temp_Avg < 65] <-
  65 - Ramona$Temp_Avg [Ramona$Temp_Avg < 65]
Ramona$Cool_Degrees [Ramona$Temp_Avg > 65] <-
  Ramona$Temp_Avg [Ramona$Temp_Avg > 65] - 65
```

``` {r create plot template}
theme_EDA <- theme_base() +
  theme(
      axis.ticks = element_line(
      color = "black"
    ),
    plot.background = element_rect(
      color = "black",
      fill = "gray"
    ),
    legend.position = "right",
    complete = TRUE
  )
theme_set(theme_EDA)
```


## Exploratory Visualizations 

```{r visualizations}
ggplot(Phoenix,
       aes(x = Date, y = Daily_Temp_Min)) +
         geom_line() + 
  geom_smooth (method = lm)+
  labs( title = "Phoenix Daily Maximum Temperatures 1980-2022")+
  geom_hline(yintercept = 65)

Three_cities <- rbind(LasVegas,
                      Phoenix,
                      SanDiego)

ggplot(Three_cities, aes(x = Date, y = Daily_Temp_Max, color = Location)) +
  geom_line() +
  geom_smooth(method=lm)
```


```{r plot heating days and cooling days, echo=FALSE}
#Create dataframes for heating and cooling days, separately
#Make one for 1980 and 2022 to compare the start and end of the time series
Phoenix_Heat_1980 <- Phoenix %>%
  group_by(Heat_Degrees) %>%
  filter(Year == "1980", Heat_Degrees != 0) %>%
  select(Date, Month, Heat_Degrees)

Phoenix_Cool_1980 <- Phoenix %>%
  group_by(Cool_Degrees) %>%
  filter(Year == "1980", Cool_Degrees != 0) %>%
  select(Date, Month, Cool_Degrees)

Phoenix_Heat_2022 <- Phoenix %>%
  group_by(Heat_Degrees) %>%
  filter(Year == "2022", Heat_Degrees != 0) %>%
  select(Date, Month, Heat_Degrees)

Phoenix_Cool_2022 <- Phoenix %>%
  group_by(Cool_Degrees) %>%
  filter(Year == "2022", Cool_Degrees != 0) %>%
  select(Date, Month, Cool_Degrees)

#Plot heating days and cooling days in separate graph bars
plot_Phoenix_1980_Heat <- ggplot(Phoenix_Heat_1980, aes(x = Month)) +
  geom_bar(fill = "red") +
  scale_x_continuous(breaks = seq_along(month.abb), labels = month.abb) +
  labs(title = "Heating Days in Phoenix, 1980", x = "Month", y = "Heating Days")
print(plot_Phoenix_1980_Heat)

plot_Phoenix_1980_Cool <- ggplot(Phoenix_Cool_1980, aes(x = Month)) +
  geom_bar(fill = "blue") +
  scale_x_continuous(breaks = seq_along(month.abb), labels = month.abb) +
  labs(title = "Cooling Days in Phoenix, 1980", x = "Month", y = "Cooling Days")

grid_Phoenix_1980_HeatCoolDays <- plot_grid(plot_Phoenix_1980_Cool, plot_Phoenix_1980_Heat)
print(grid_Phoenix_1980_HeatCoolDays)

#2022 plots
plot_Phoenix_2022_Heat <- ggplot(Phoenix_Heat_2022, aes(x = Month)) +
  geom_bar(fill = "red") +
  scale_x_continuous(breaks = seq_along(month.abb), labels = month.abb) +
  labs(title = "Heating Days in Phoenix, 2022", x = "Month", y = "Heating Days")
print(plot_Phoenix_2022_Heat)

plot_Phoenix_2022_Cool <- ggplot(Phoenix_Cool_2022, aes(x = Month)) +
  geom_bar(fill = "blue") +
  scale_x_continuous(breaks = seq_along(month.abb), labels = month.abb) +
  labs(title = "Cooling Days in Phoenix, 2022", x = "Month", y = "Cooling Days")

grid_Phoenix_2022_HeatCoolDays <- plot_grid(plot_Phoenix_2022_Cool, plot_Phoenix_2022_Heat)
print(grid_Phoenix_2022_HeatCoolDays)

#Put the heating and cool days on the same graph
plot_Phoenix_1980_HeatCoolDays <- ggplot() +
  geom_bar(data = Phoenix_Cool_1980, aes(x = Month, fill = "Cooling Days")) +
  geom_bar(data = Phoenix_Heat_1980, aes(x = Month, fill = "Heating Days")) +
  scale_x_continuous(breaks = seq_along(month.abb), labels = month.abb) +
  labs(title = "Cooling and Heating Days in Phoenix, 1980", x = "Month", y = "Cooling or Heating Days") + 
  scale_fill_manual(values = c("blue", "red"))
print(plot_Phoenix_1980_HeatCoolDays)

plot_Phoenix_2022_HeatCoolDays <- ggplot() +
  geom_bar(data = Phoenix_Cool_2022, aes(x = Month, fill = "Cooling Days")) +
  geom_bar(data = Phoenix_Heat_2022, aes(x = Month, fill = "Heating Days")) +
  scale_x_continuous(breaks = seq_along(month.abb), labels = month.abb) +
  labs(title = "Cooling and Heating in Phoenix, 2022", x = "Month", y = "Cooling or Heating Days") + 
  scale_fill_manual(values = c("blue", "red"))
print(plot_Phoenix_2022_HeatCoolDays)
```

```{r save files}
write.csv <- 
write.csv <- 
write.csv <- 
write.csv <- 
write.csv <- 
write.csv <- 
```