---
title: "Data Wrangling"
author: "Candela Cerpa & Samantha Pace & Vinny Whatley"
date: "2023-11-20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("tidyverse")
#install.packages("lubridate")
#install.packages("here")
#install.packages("zoo")

library(tidyverse)
library(lubridate)
library(here)
library(zoo)

here()
```

```{r data wrangling}
Phoenix <- read.csv(here("./Data/Raw/phoenix_fountainhills_raw.csv"),
                    stringsAsFactors = TRUE) %>% 
  filter(NAME == "PHOENIX AIRPORT, AZ US") %>% 
  select(NAME, DATE, TMAX, TMIN, TAVG) %>% 
  mutate(DATE = ymd(DATE)) %>%
  mutate(NAME = "Phoenix") %>%
  mutate(Month = month(DATE)) %>%
  mutate(Year = year(DATE)) %>%
  mutate(DayofYear = yday(DATE))

FountainHills <- read.csv(here("./Data/Raw/phoenix_fountainhills_raw.csv"),
                          stringsAsFactors = TRUE) %>% 
  filter(NAME == "FOUNTAIN HILLS, AZ US") %>% 
  select(NAME, DATE, TMAX, TMIN, TAVG) %>% 
  mutate(DATE = ymd(DATE)) %>%
  mutate(NAME = "Fountain Hills") %>%
  mutate(Month = month(DATE)) %>%
  mutate(Year = year(DATE)) %>%
  mutate(DayofYear = yday(DATE))

LasVegas <- read.csv(here("./Data/Raw/Nevada_data_raw.csv"),
                     stringsAsFactors = TRUE) %>% 
  filter(NAME == "MCCARRAN INTERNATIONAL AIRPORT, NV US") %>% 
  select(NAME, DATE, TMAX, TMIN, TAVG) %>% 
  mutate(DATE = ymd(DATE)) %>%
  mutate(NAME = "Las Vegas") %>%
  mutate(Month = month(DATE)) %>%
  mutate(Year = year(DATE)) %>%
  mutate(DayofYear = yday(DATE))

Pahrump <- read.csv(here("./Data/Raw/Nevada_data_raw.csv"),
                    stringsAsFactors = TRUE) %>% 
  filter(NAME == "PAHRUMP 4 NW, NV US") %>% 
  select(NAME, DATE, TMAX, TMIN, TAVG) %>% 
  mutate(DATE = ymd(DATE)) %>%
  mutate(NAME = "Pahrump") %>%
  mutate(Month = month(DATE)) %>%
  mutate(Year = year(DATE)) %>%
  mutate(DayofYear = yday(DATE))

SanDiego <- read.csv(here("./Data/Raw/SanDiego_Ramona_Raw_Data.csv"),
                     stringsAsFactors = TRUE) %>% 
  filter(NAME == "SAN DIEGO INTERNATIONAL AIRPORT, CA US") %>% 
  select(NAME, DATE, TMAX, TMIN, TAVG) %>% 
  mutate(DATE = mdy(DATE)) %>%
  mutate(NAME = "San Diego") %>%
  mutate(Month = month(DATE)) %>%
  mutate(Year = year(DATE)) %>%
  mutate(DayofYear = yday(DATE))

Ramona <- read.csv(here("./Data/Raw/SanDiego_Ramona_Raw_Data.csv"),
                   stringsAsFactors = TRUE) %>% 
  filter(NAME == "RAMONA AIRPORT, CA US") %>% 
  select(NAME, DATE, TMAX, TMIN, TAVG) %>% 
  mutate(DATE = mdy(DATE)) %>%
  mutate(NAME = "Ramona") %>%
  mutate(Month = month(DATE)) %>%
  mutate(Year = year(DATE)) %>%
  mutate(DayofYear = yday(DATE))
```

## Editting the Column Names

```{r update column names, echo=FALSE}
colnames(Phoenix) <-
  c("Location", "Date", "Daily_Temp_Max", "Daily_Temp_Min", "Temp_Avg", 
    "Month", "Year", "DayofYear")

colnames(FountainHills) <-
  c("Location", "Date", "Daily_Temp_Max", "Daily_Temp_Min", "Temp_Avg", 
    "Month", "Year", "DayofYear")

colnames(LasVegas) <-
  c("Location", "Date", "Daily_Temp_Max", "Daily_Temp_Min", "Temp_Avg", 
    "Month", "Year", "DayofYear")

colnames(Pahrump) <-
  c("Location", "Date", "Daily_Temp_Max", "Daily_Temp_Min", "Temp_Avg", 
    "Month", "Year", "DayofYear")

colnames(SanDiego) <-
  c("Location", "Date", "Daily_Temp_Max", "Daily_Temp_Min", "Temp_Avg", 
    "Month", "Year", "DayofYear")

colnames(Ramona) <-
  c("Location", "Date", "Daily_Temp_Max", "Daily_Temp_Min", "Temp_Avg", 
    "Month", "Year", "DayofYear")
```

```{r data summaries}
# Determining which locations and columns have the most NA's for max and min
#daily temperatures, therefore determining which to interpolate
summary(Phoenix)
summary(FountainHills)
summary(LasVegas)
summary(Pahrump)
summary(SanDiego)
summary(Ramona)
```

```{r linear interpolation}
# FountainHills, Pahrump, Ramona requires interpolation for the min and max temps

# Linear interpolation for Fountain Hills
FountainHills <-
  FountainHills %>% 
  mutate(Daily_Temp_Max = na.approx(Daily_Temp_Max), 
         Daily_Temp_Min = na.approx(Daily_Temp_Min))

# Showing that there are no longer NA's in either of these columns.
summary(Phoenix$Daily_Temp_Max)
summary(Phoenix$Daily_Temp_Min)

# Linear interpolation for Pahrump
Pahrump <-
  Pahrump %>% 
  mutate(Daily_Temp_Max = na.approx(Daily_Temp_Max), 
         Daily_Temp_Min = na.approx(Daily_Temp_Min))

# Showing that there are no longer NA's in either of these columns.
summary(Pahrump$Daily_Temp_Max)
summary(Pahrump$Daily_Temp_Min)

# Linear interpolation for Ramona
Ramona <-
  Ramona %>% 
  mutate(Daily_Temp_Max = na.approx(Daily_Temp_Max), 
         Daily_Temp_Min = na.approx(Daily_Temp_Min))

# Showing that there are no longer NA's in either of these columns.
summary(Ramona$Daily_Temp_Max)
summary(Ramona$Daily_Temp_Min)
```

```{r updating the average columns}
Phoenix$Temp_Avg <- 
  rowMeans(Phoenix [, c(3, 4)], na.rm = TRUE)

FountainHills$Temp_Avg <- 
  rowMeans(FountainHills [, c(3, 4)], na.rm = TRUE)

Pahrump$Temp_Avg <- 
  rowMeans(Pahrump [, c(3, 4)], na.rm = TRUE)

LasVegas$Temp_Avg <- 
  rowMeans(LasVegas [, c(3, 4)], na.rm = TRUE)

SanDiego$Temp_Avg <- 
  rowMeans(SanDiego [, c(3, 4)], na.rm = TRUE)

Ramona$Temp_Avg <- 
  rowMeans(Ramona [, c(3, 4)], na.rm = TRUE)
```

```{r Calculating Heating and Cooling Degree Days}
#1. Create a column for heating degrees with 0s
#2. Create a column for heating degrees with 0s
#3. Calculate heating degrees by finding the mean temp that's below 65F then
#subtracting the mean temp from 65
#4. Calculate cooling degrees by finding the mean temp that's above 65F then
#subtracting 65 from the mean temp

Phoenix$Heat_Degrees <- rep(0)
Phoenix$Cool_Degrees <- rep(0)
Phoenix$Heat_Degrees [Phoenix$Temp_Avg < 65] <-
  65 - Phoenix$Temp_Avg [Phoenix$Temp_Avg < 65]
Phoenix$Cool_Degrees [Phoenix$Temp_Avg > 65] <-
  Phoenix$Temp_Avg [Phoenix$Temp_Avg > 65] - 65

FountainHills$Heat_Degrees <- rep(0)
FountainHills$Cool_Degrees <- rep(0)
FountainHills$Heat_Degrees [FountainHills$Temp_Avg < 65] <-
  65 - FountainHills$Temp_Avg [FountainHills$Temp_Avg < 65]
FountainHills$Cool_Degrees [FountainHills$Temp_Avg > 65] <-
  FountainHills$Temp_Avg [FountainHills$Temp_Avg > 65] - 65

LasVegas$Heat_Degrees <- rep(0)
LasVegas$Cool_Degrees <- rep(0)
LasVegas$Heat_Degrees [LasVegas$Temp_Avg < 65] <-
  65 - LasVegas$Temp_Avg [LasVegas$Temp_Avg < 65]
LasVegas$Cool_Degrees [LasVegas$Temp_Avg > 65] <-
  LasVegas$Temp_Avg [LasVegas$Temp_Avg > 65] - 65

Pahrump$Heat_Degrees <- rep(0)
Pahrump$Cool_Degrees <- rep(0)
Pahrump$Heat_Degrees [Pahrump$Temp_Avg < 65] <-
  65 - Pahrump$Temp_Avg [Pahrump$Temp_Avg < 65]
Pahrump$Cool_Degrees [Pahrump$Temp_Avg > 65] <-
  Pahrump$Temp_Avg [Pahrump$Temp_Avg > 65] - 65

SanDiego$Heat_Degrees <- rep(0)
SanDiego$Cool_Degrees <- rep(0)
SanDiego$Heat_Degrees [SanDiego$Temp_Avg < 65] <-
  65 - SanDiego$Temp_Avg [SanDiego$Temp_Avg < 65]
SanDiego$Cool_Degrees [SanDiego$Temp_Avg > 65] <-
  SanDiego$Temp_Avg [SanDiego$Temp_Avg > 65] - 65

Ramona$Heat_Degrees <- rep(0)
Ramona$Cool_Degrees <- rep(0)
Ramona$Heat_Degrees [Ramona$Temp_Avg < 65] <-
  65 - Ramona$Temp_Avg [Ramona$Temp_Avg < 65]
Ramona$Cool_Degrees [Ramona$Temp_Avg > 65] <-
  Ramona$Temp_Avg [Ramona$Temp_Avg > 65] - 65
```

```{r save processed data, echo=FALSE}
write.csv(Phoenix, 
          file = "./Data/Processed/PhoenixAZ_processed.csv")

write.csv(FountainHills, 
          file = "./Data/Processed/FountainHillsAZ_processed.csv")

write.csv(LasVegas, 
          file = "./Data/Processed/LasVegasNV_processed.csv")

write.csv(Pahrump,
          file = "./Data/Processed/PahrumpNV_processed.csv")

write.csv(SanDiego,
          file = "./Data/Processed/SanDiegoCA_processed.csv")

write.csv(Ramona,
          file = "./Data/Processed/RamonaCA_processed.csv")
```
